# Generated by Django 5.2.7 on 2025-10-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformanalytics',
            index=models.Index(fields=['platform_content', '-recorded_at'], name='platform_an_platfor_55186b_idx'),
        ),
        migrations.AddIndex(
            model_name='platformanalytics',
            index=models.Index(fields=['platform', 'metric_type'], name='platform_an_platfor_bf8bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['user', 'platform'], name='platform_co_user_id_de60f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformconnection',
            unique_together={('user', 'platform')},
        ),
    ]
