# Generated by Django 5.2.7 on 2025-10-26 06:58

import apps.links.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('is_unique', models.BooleanField(default=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'link_clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackableLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('short_code', models.CharField(default=apps.links.models.generate_short_code, max_length=50, unique=True)),
                ('destination_url', models.URLField()),
                ('custom_slug', models.CharField(blank=True, max_length=255)),
                ('clicks', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.contentblock')),
            ],
            options={
                'db_table': 'trackable_links',
                'ordering': ['-created_at'],
            },
        ),
    ]
