# Generated by Django 5.2.7 on 2025-10-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackablelink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackable_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_detail', to='links.trackablelink'),
        ),
        migrations.AddIndex(
            model_name='trackablelink',
            index=models.Index(fields=['short_code'], name='trackable_l_short_c_ac8152_idx'),
        ),
        migrations.AddIndex(
            model_name='trackablelink',
            index=models.Index(fields=['user', '-created_at'], name='trackable_l_user_id_48babe_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['link', '-clicked_at'], name='link_clicks_link_id_01f19e_idx'),
        ),
        migrations.AddIndex(
            model_name='linkclick',
            index=models.Index(fields=['country'], name='link_clicks_country_87e4a6_idx'),
        ),
    ]
