# Generated by Django 5.2.7 on 2025-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackablelink',
            name='campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trackablelink',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackablelink',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
