# Generated by Django 5.2.7 on 2025-10-26 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('country', models.CharField(default='us', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('trend_direction', models.CharField(blank=True, max_length=20)),
                ('platform_breakdown', models.JSONField(blank=True, default=dict)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('prepositions', models.JSONField(blank=True, default=list)),
                ('alphabetical', models.JSONField(blank=True, default=list)),
                ('comparisons', models.JSONField(blank=True, default=list)),
                ('related_keywords', models.JSONField(blank=True, default=list)),
                ('viral_examples', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'keyword_research',
                'ordering': ['-created_at'],
            },
        ),
    ]
