# Generated by Django 5.2.7 on 2025-10-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordresearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_research', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='keywordresearch',
            index=models.Index(fields=['keyword'], name='keyword_res_keyword_c2ee1b_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresearch',
            index=models.Index(fields=['user', 'keyword'], name='keyword_res_user_id_a6547e_idx'),
        ),
    ]
