# Generated by Django 5.2.7 on 2025-10-26 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('colors', models.JSONField(blank=True, default=dict)),
                ('fonts', models.JSONField(blank=True, default=dict)),
                ('watermark_settings', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brand_kits',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('keyword_text', models.CharField(blank=True, max_length=255)),
                ('niche', models.CharField(blank=True, max_length=100)),
                ('content_angle', models.CharField(blank=True, max_length=100)),
                ('tone', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('total_reach', models.IntegerField(default=0)),
                ('total_engagement', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_blocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_url', models.URLField()),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('folder', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image_library',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('blog', 'Blog')], max_length=50)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('content_data', models.JSONField(blank=True, default=dict)),
                ('images', models.JSONField(blank=True, default=list)),
                ('video_script', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('trackable_link', models.CharField(blank=True, max_length=500)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reach', models.IntegerField(default=0)),
                ('engagement', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_content',
                'ordering': ['-created_at'],
            },
        ),
    ]
