# Generated by Django 5.2.7 on 2025-10-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('keywords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brandkit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.keywordresearch'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagelibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformcontent',
            name='content_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_versions', to='content.contentblock'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['user', '-created_at'], name='content_blo_user_id_7f6644_idx'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['status'], name='content_blo_status_6e639a_idx'),
        ),
        migrations.AddIndex(
            model_name='imagelibrary',
            index=models.Index(fields=['user', '-created_at'], name='image_libra_user_id_efad3b_idx'),
        ),
        migrations.AddIndex(
            model_name='platformcontent',
            index=models.Index(fields=['content_block', 'platform'], name='platform_co_content_fab9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='platformcontent',
            index=models.Index(fields=['platform'], name='platform_co_platfor_cb443c_idx'),
        ),
    ]
