# Generated by Django 5.0 on 2025-10-28 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtDirectionPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("minimalistic", "Minimalistic"),
                            ("retro", "Retro"),
                            ("vintage", "Vintage"),
                            ("pop", "Pop Art"),
                            ("modern", "Modern"),
                            ("elegant", "Elegant"),
                            ("bold", "Bold"),
                            ("playful", "Playful"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("prompt_template", models.TextField()),
                ("color_palette", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "art_direction_presets",
            },
        ),
        migrations.CreateModel(
            name="ReferenceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="references/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("extracted_text", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reference_files",
                "ordering": ["-created_at"],
            },
        ),
    ]
